-- Add profile fields to users table
ALTER TABLE users ADD COLUMN phone VARCHAR(20) DEFAULT NULL AFTER role;
ALTER TABLE users ADD COLUMN address VARCHAR(255) DEFAULT NULL AFTER phone;
ALTER TABLE users ADD COLUMN city VARCHAR(120) DEFAULT NULL AFTER address;
ALTER TABLE users ADD COLUMN profile_pic VARCHAR(255) DEFAULT NULL AFTER city;
